
FROM node:14


WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


ARG NEXT_PUBLIC_API_CRUD
ARG NEXT_PUBLIC_API_CRUD_COGNITO_ID
ARG NEXT_PUBLIC_API_CRUD_CLIENT_ID
ARG NEXT_PUBLIC_API_CRUD_REGINO


ENV NEXT_PUBLIC_API_CRUD=$NEXT_PUBLIC_API_CRUD
ENV NEXT_PUBLIC_API_CRUD_COGNITO_ID=$NEXT_PUBLIC_API_CRUD_COGNITO_ID
ENV NEXT_PUBLIC_API_CRUD_CLIENT_ID=$NEXT_PUBLIC_API_CRUD_CLIENT_ID
ENV NEXT_PUBLIC_API_CRUD_REGINO=$NEXT_PUBLIC_API_CRUD_REGINO

# Next.js
RUN npm run build


EXPOSE 3000


CMD ["npm", "start"]